name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no goldstation@65.21.247.82 'echo "SSH connection successful!"'
        
    - name: Verify Server Repository State
      run: |
        ssh -o StrictHostKeyChecking=no goldstation@65.21.247.82 'cd /home/goldstation/public_html/backend && git remote -v && git status'
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no goldstation@65.21.247.82 'cd /home/goldstation/public_html/backend && git fetch origin && git reset --hard origin/main && git clean -fd'
        ssh -o StrictHostKeyChecking=no goldstation@65.21.247.82 'cd /home/goldstation/public_html/backend && git log -1 --oneline'

    - name: Run Migrations
      run: |
        ssh -o StrictHostKeyChecking=no goldstation@65.21.247.82 'cd /home/goldstation/public_html/backend && php artisan migrate --force'